[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  # VITE_BACKEND_URL = "https://tu-backend-en-produccion.com"  # Configurar en Netlify Dashboard

# Proxy API requests to backend
[[redirects]]
  from = "/api/*"
  to = "https://back-landing-kia.onrender.com/api/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
