[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  # VITE_BACKEND_URL = "https://tu-backend-en-produccion.com"  # Configurar en Netlify Dashboard

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
